export declare class abDate_Class {
    #private;
    span_Minute: number;
    span_Hour: number;
    span_Day: number;
    formats_Date: string;
    formats_DateTime: string;
    formats_Time: string;
    formats_Time_WithSeconds: string;
    get utcOffset(): void;
    constructor();
    format(time: number, format: string, timezone?: string | null): string;
    format_Date(time: number, timezone?: string | null): string;
    format_Date_UTC(time: number): string;
    format_DateTime(time: number, timezone?: string | null): string;
    format_DateTime_UTC(time: number): string;
    format_Time(time: number, withSeconds?: boolean, timezone?: string | null): string;
    format_UTC(time: number, format: string): string;
    getDate(time?: number | null): Date;
    getDay(time?: number | null): number;
    getDay_UTC(time?: number | null): number;
    getDayOfWeek(time?: number | null): number;
    getDayOfWeek_UTC(time: number): number;
    getDayNr(time?: number | null): number;
    getDayNr_UTC(time?: number | null): number;
    getDaysCountInMonth(time?: number | null): number;
    getDaysCountInMonth_UTC(time?: number | null): number;
    getMonth(time?: number | null): number;
    getMonth_UTC(time?: number | null): number;
    getMonthNr(time?: number | null): number;
    getMonthNr_UTC(time?: number | null): number;
    getTime(date?: Date): number;
    getTime_Rel(time?: number | null): number;
    getUTCOffset(time?: number | null): number;
    getUTCOffset_Time(time?: number | null): number;
    getYearNr(time?: number | null): number;
    getYearNr_UTC(time?: number | null): number;
    setTimezone(timezone: string): void;
    strToTime(str: string, timeFormat: string): number | null;
    strToTime_UTC(str: string, timeFormat: string): number | null;
    strToTime_Date(str: string): number | null;
    strToTime_Date_UTC(str: string): number | null;
    strToTime_DateTime(str: string): number | null;
    strToTime_DateTime_UTC(str: string): number | null;
    strToTime_Time(str: string, withSeconds?: boolean): number | null;
}
declare const abDate: abDate_Class;
export default abDate;
